/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;
using Thrift.Transports;
using Thrift.Transports.Client;
using Thrift.Transports.Server;



/// <summary>
/// Atomic mutation for the specified row. It can be either Put or Delete.
/// </summary>
public partial class TMutation : TBase
{
  private TPut _put;
  private TDelete _deleteSingle;

  public TPut Put
  {
    get
    {
      return _put;
    }
    set
    {
      __isset.put = true;
      this._put = value;
    }
  }

  public TDelete DeleteSingle
  {
    get
    {
      return _deleteSingle;
    }
    set
    {
      __isset.deleteSingle = true;
      this._deleteSingle = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool put;
    public bool deleteSingle;
  }

  public TMutation()
  {
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct)
            {
              Put = new TPut();
              await Put.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.Struct)
            {
              DeleteSingle = new TDelete();
              await DeleteSingle.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("TMutation");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if (Put != null && __isset.put)
      {
        field.Name = "put";
        field.Type = TType.Struct;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await Put.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (DeleteSingle != null && __isset.deleteSingle)
      {
        field.Name = "deleteSingle";
        field.Type = TType.Struct;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await DeleteSingle.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString()
  {
    var sb = new StringBuilder("TMutation(");
    bool __first = true;
    if (Put != null && __isset.put)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Put: ");
      sb.Append(Put== null ? "<null>" : Put.ToString());
    }
    if (DeleteSingle != null && __isset.deleteSingle)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("DeleteSingle: ");
      sb.Append(DeleteSingle== null ? "<null>" : DeleteSingle.ToString());
    }
    sb.Append(")");
    return sb.ToString();
  }
}

