/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;
using System.ServiceModel;
using System.Runtime.Serialization;

using Thrift.Protocols;
using Thrift.Protocols.Entities;
using Thrift.Protocols.Utilities;
using Thrift.Transports;
using Thrift.Transports.Client;
using Thrift.Transports.Server;


namespace tutorial
{

  /// <summary>
  /// Structs can also be exceptions, if they are nasty.
  /// </summary>
  public partial class InvalidOperation : TException, TBase
  {
    private int _whatOp;
    private string _why;

    [DataMember(Order = 0)]
    public int WhatOp
    {
      get
      {
        return _whatOp;
      }
      set
      {
        __isset.whatOp = true;
        this._whatOp = value;
      }
    }

    [DataMember(Order = 0)]
    public string Why
    {
      get
      {
        return _why;
      }
      set
      {
        __isset.why = true;
        this._why = value;
      }
    }


    [DataMember(Order = 1)]
    public Isset __isset;
    [DataContract]
    public struct Isset
    {
      [DataMember]
      public bool whatOp;
      [DataMember]
      public bool why;
    }

    #region XmlSerializer support

    public bool ShouldSerializeWhatOp()
    {
      return __isset.whatOp;
    }

    public bool ShouldSerializeWhy()
    {
      return __isset.why;
    }

    #endregion XmlSerializer support

    public InvalidOperation()
    {
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32)
              {
                WhatOp = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                Why = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("InvalidOperation");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        if (__isset.whatOp)
        {
          field.Name = "whatOp";
          field.Type = TType.I32;
          field.ID = 1;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI32Async(WhatOp, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (Why != null && __isset.why)
        {
          field.Name = "why";
          field.Type = TType.String;
          field.ID = 2;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(Why, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString()
    {
      var sb = new StringBuilder("InvalidOperation(");
      bool __first = true;
      if (__isset.whatOp)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("WhatOp: ");
        sb.Append(WhatOp);
      }
      if (Why != null && __isset.why)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Why: ");
        sb.Append(Why);
      }
      sb.Append(")");
      return sb.ToString();
    }
  }


  [DataContract]
  public partial class InvalidOperationFault
  {
    private int _whatOp;
    private string _why;

    [DataMember(Order = 0)]
    public int WhatOp
    {
      get
      {
        return _whatOp;
      }
      set
      {
        this._whatOp = value;
      }
    }

    [DataMember(Order = 0)]
    public string Why
    {
      get
      {
        return _why;
      }
      set
      {
        this._why = value;
      }
    }

  }

}
